### ISSUE TITLE
[Feature Request]: Backlinks for canvas

### ISSUE THREAD

**Issue by wwjCMP** [aqav/obsidian-canvas-links#4]
Display which file or canvas the current canvas is referenced by.

**Comment by aqav** [comment]
@wwjCMP 

![image](https://github.com/aqav/obsidian-canvas-links/assets/66734646/449408d3-7690-4721-9ad3-102fc6ed559d)

I think this feature has been implemented. Do I miss your point? It would have been helpful if you had described your request more explicit.

**Comment by wwjCMP** [comment]
Show the files or canvas that this canvas was embedded in. 
![Snipaste_2023-06-24_17-46-39](https://github.com/aqav/obsidian-canvas-links/assets/32979859/962a944d-91a7-4d89-9eb1-e266cfc524d9)

**Comment by aqav** [comment]
@wwjCMP 
Plz describe more explicit, like "The active editor is showing the Canvas X, there is a Canvas Y contained in it, then I ..." or more screenshot. Because I still do not take your point by your comment(just a simple statement and pic)

By my screenshot. the canvas 1 is embedded in the canvas 2, and when I switch the active editor to canvas 1, then the view "Canvas the file embedded" is showing the canvas 2 in the list(what the red cube mark). So I think the requirement "Show the files or canvas that this canvas was embedded in." is implemented

**Comment by wwjCMP** [comment]
What i mean is, file A ( canvas 1, canvas 2), activate canvas 1,  displays file A in sidebar.
  
Now canvas 1 (file B), activate file B, display canvas 1 in sidebar.
And canvas 1 (file B), activate canvas1, display file B in sidebar.

**Comment by aqav** [comment]
"Now canvas 1 (file B), activate file B, display canvas 1 in sidebar.
And canvas 1 (file B), activate canvas1, display file B in sidebar."

Yes, the plugin is designed for this way. In the Obsidian without this plugin, core plugin "outgoing links" and "backlinks" only work when the file link to other file by "[[]]", and this plugin add two view to show "which files the canvas contain" and "which canvases the file embedded in" to display the connection link by "Contain in". 
As your comment, the canvas 1 contain file B, when you active the file B, the canvas 1 should display in the view "Canvas the file embedded"; when you active the canvas 1, the file B should display in the view "Files the canvas contain". I don't see any wrong that don't follow the purpose the plugin should be.
May be this article will help you to understand why I create this plugin. https://forum.obsidian.md/t/canvas-cards-and-notes-in-links-backlinks-and-outgoing-arrows-from-canvas-in-graph-view/49697

"file A ( canvas 1, canvas 2), activate canvas 1, displays file A in sidebar"
How file A contain canvas 1 and canvas 2?
Do you mean there are links "[[canvas 1]], [[canvas 2]]" in the file A? 
The "[[]]" link is already handle by Obsidian core plugins "outgoing links" and "Backlinks"(like screenshot below), Can you plz check it first?
![image](https://github.com/aqav/obsidian-canvas-links/assets/66734646/415fca68-015d-4123-9e20-430b5951ca18)

**Comment by wwjCMP** [comment]
The plugin is not working in Obsidian v1.7.5.
